// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ab579af9-4c61-4ee1-a6bc-85764ecb16a9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDelayChange();
void onPressureChange();
void onRPMChange();
void onSpO2Change();

float _delay_;
float pressure;
float rPM;
float spO2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(_delay_, READWRITE, ON_CHANGE, onDelayChange);
  ArduinoCloud.addProperty(pressure, READWRITE, ON_CHANGE, onPressureChange);
  ArduinoCloud.addProperty(rPM, READWRITE, ON_CHANGE, onRPMChange);
  ArduinoCloud.addProperty(spO2, READWRITE, ON_CHANGE, onSpO2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
